### ISSUE TITLE
Modbus times out after 1 minute?

### ISSUE THREAD

**Issue by JH22ZH** [HumaRobotics/modbus#3]
Hello, I'm using this with ROS kinetic and a Siemens S7-1200 PLC for a school project and Publishing and Subscribing works. However after 1 minute consistently, the Modbus on ROS side will disconnect. I looked through the code but I'm not sure what variable/program needs to be adjusted to prevent this. May I know which one please? 

Thank you.

**Comment by JH22ZH** [comment]
I have managed to fix the issue, I just had to turn off the firewall on the router connecting the PLC and the ROS Computer! Hope this helps anyone else facing the same problem.

**Comment by Philippe-Capdepuy** [comment]
Glad you solved it, thx for the feedback.
I would have suggested to make sure that you have constant 2 way communication between the two devices to keep the connection alive. The issue was probably a timeout due to inactivity on one side, maybe a consequence of the firewall indeed.
